clone_depth: 50

environment:
  PYTHON: C:\Python37-x64
  EXECUTABLE: python.exe
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GENERATOR: "Visual Studio 15 2017"

install:
  - '%PYTHON%\%EXECUTABLE% --version'

build_script:
  - '%PYTHON%\%EXECUTABLE% build.py'

