language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      addons:
        homebrew:
          update: true
          packages:
            - python3
          casks:
            - packages
    - os: linux
      dist: trusty
      sudo: required
      python: '3.7'
      addons:
        apt:
          sources:
            - sourceline: 'ppa:deadsnakes/ppa'
          packages:
            - python3.7
            - clang
            - freeglut3-dev
            - libasound2-dev
            - libcurl4-openssl-dev
            - libfreetype6-dev
            - libjack-jackd2-dev
            - libx11-dev
            - libxcomposite-dev
            - libxcursor-dev
            - libxinerama-dev
            - libxrandr-dev
            - mesa-common-dev
            - libwebkit2gtk-3.0-dev
            - ladspa-sdk

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0                            ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start                    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sleep 3                                         ; fi

script:
  - cmake --version
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python3.7 --version; else python3 --version; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python3.7 ci/all.py: else python3 ci/all.py; fi

deploy:
  provider: releases
  api_key:
    secure: 'kfjk90D/6pw+ZpXXHlnGhbYcjMR5iDLUECCEvUCLW9A7aTIkHC16IuaLIurZbRMZr7TnnVjocNJMlIAr71Am+XC1INEUdC9SGOwCMx/Wa5pAhspNgF/PpzDMuNc56xfeQff870ju9i7deUlYFSqthX79BeLpnArNVybEDh61Q0RQNRTtTG4EdbIWsYBybylAaAnoN49ZXJq9d59z9D4YPCM+CEIQXCVclxh4cdk8GOPcaOQb0fvGeVCjOgA5uFaCFZfb6adoVKZ2G9iQIgqgFXsZa1mhvAEIDBIfQjh+UutL5itMipwZOB4NQUUsezPFVL94z9v86X5NLwOgHinZ3SzEz4zUksg4HrimrNvjWMbH9Y177gh1aWtoClYmPEq0bqc+tqMgCT75i5DBGP7bNHgqz98GhQ9VWef8d79Jm3H1OAzaCLidwrIj0W34jN7MFwCCryFqqocAtbdcE1ffW5RwCHwWh/PafQE6scP87hm9vbldz7vX0ddPGGz8fwHMpPE9z1+CjpEUe1FRd3GvmLRgqmTrlLkvAIE6ZSr4vxUN4Iujerbn/oGmknwvN+FarQPe/l7TiUdPQRp3NVna5Kw1dP3rJZ+wHVK0qbpselKSXw0tDcTSlv5wyR7ypWXo7YyBcGkXMLKsRazuH9WWW/7olCSC3Ka/G8WGQ+32mX8='
  name: 'Meeblip Controller ${TRAVIS_TAG}'
  body: 'Changelog'
  file_glob: true
  file:
    - 'build/installer/output/*.zip'
    - 'build/installer/output/*.AppImage'
  skip_cleanup: true
  draft: true
  prerelease: false
  on:
    tags: true

