language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      addons:
        homebrew:
          packages:
            - python3

script:
  - cmake --version
  - python3 --version
  - python3 build.py

