language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      addons:
        homebrew:
          update: true
          packages:
            - python3
          casks:
            - packages

script:
  - cmake --version
  - python3 --version
  - python3 build.py

